### ISSUE TITLE
在windows10 1803(最新正式版)中文显示有问题

### ISSUE THREAD

**Issue by mxsail** [mskyaxl/wsl-terminal#101]
![image](https://user-images.githubusercontent.com/28945708/40289698-73e9705e-5cec-11e8-9108-5d4773ea07d5.png)
![image](https://user-images.githubusercontent.com/28945708/40289700-769ca23a-5cec-11e8-96fb-bf1d3782be44.png)

**Comment by ZeppLu** [comment]
came across the same issue

![image](https://user-images.githubusercontent.com/17007549/41193125-e41024c4-6c3a-11e8-87b0-30cb63602003.png)
