### ISSUE TITLE
固定任务栏问题

### ISSUE THREAD

**Issue by CyshallChan** [mskyaxl/wsl-terminal#103]
系统：Windows10 1803
open-wsl：0811
固定到任务栏然后重新打开会出现如下图的错误，请问有什么办法可以解决么？
![image](https://user-images.githubusercontent.com/22564041/40594388-80bebf8a-6261-11e8-86f2-7d77f045cc21.png)

**Comment by mapan1984** [comment]
右键点击固定的任务栏图标，之后右键点击`wsl-terminal`，选择`属性`，修改属性中的`target`（目标）为:

    C:\wsl-terminal\bin\mintty.exe  --wsl --rootfs=// --configdir "C:\wsl-terminal\etc" -i "C:\wsl-terminal\open-wsl.exe"  -t "Bash on Ubuntu" -e /bin/wslbridge  -e SHELL="/bin/bash" -e LANG -t -e USE_TMUX=1 /bin/bash

我把`wsl-terminal`解压放置在`C:\wsl-terminal`目录，默认启动Tmux，你可以根据你的需要改上面的命令

**Comment by CyshallChan** [comment]
@mapan1984 万分感谢！不过还是建议作者能调整一下。

**Comment by zxbu** [comment]
我把@mapan1984的操作步骤完善一下
1. 先打开wsl终端，然后固定到任务栏
2. 右键刚才固定的任务栏图标，在弹出来的小窗里再右键Terminal，选择属性
3. 右键wsl-terminal目录下的wsl-terminal快捷方式选择属性，把里面的目标全选复制到第2步打开的属性里

搞定！

**Comment by CyshallChan** [comment]
这个问题新版本已经解决。
