### ISSUE TITLE
Solarized-light配色和vim的solarized搭配时有问题

### ISSUE THREAD

**Issue by SmartFan** [mskyaxl/wsl-terminal#107]
将控制台配色设置为solarized-light，vim配色设置为solarized时会出现如下的情况：
Set console theme to solarized-light and vim theme to solarized dark/light, here's what I get:
![image](https://user-images.githubusercontent.com/18050364/41350218-f708c0c4-6f44-11e8-9da4-bd4f95d024ff.png)
![image](https://user-images.githubusercontent.com/18050364/41350229-01c41644-6f45-11e8-80d8-23933ca0cf7e.png)
图中高亮的行是dark和light的设置，和效果似乎反过来了。
Highlighted line sets vim theme to dark/light but the outcomes seem inversed.
不过，如果控制台的配色设置为solarized-dark，则vim的solarized主题也可以正常作用。
Meanwhile, vim solarized themes work well with console solarized-dark theme.
如何解决这个问题呢？
Is there a way to solve this?

**Comment by HankelBao** [comment]
你可以试试base16-shell，可以和vim配合使用

**Comment by mskyaxl** [comment]
I am actually using solarized for a while and this is what's working for me

set t_Co =256 
syntax enable
let g:solarized_termcolors=256
set background=dark

(you can also find it in: https://github.com/mskyaxl/dotfiles/blob/master/vim/vimrc ) 

I am using the default mintty theme and it looks like this

![image](https://user-images.githubusercontent.com/5708771/79067655-42d4dc00-7cc1-11ea-9863-f168156754b6.png)

![image](https://user-images.githubusercontent.com/5708771/79067662-4b2d1700-7cc1-11ea-8b23-3ead2596b160.png)

Probably with a better theme you can get closer to what's shown in the screenshots on solarized website.

**Comment by mskyaxl** [comment]
or even better, you keep only 
syntax enable
set background=dark

but use one of the themes from here:

https://github.com/karlin/mintty-colors-solarized

and you get something like this:
![image](https://user-images.githubusercontent.com/5708771/79074575-82192200-7ced-11ea-8fc7-ec7967565ed6.png)
![image](https://user-images.githubusercontent.com/5708771/79074594-9826e280-7ced-11ea-8ec0-ada20b5bfc9b.png)
