### ISSUE TITLE
how to use cmdtool

### ISSUE THREAD

**Issue by pinggit** [mskyaxl/wsl-terminal#108]
readme里提到的这个cmdtool到底怎么用啊？
迷惑

运行结果：
···
$ ./cmdtool
bash: ./cmdtool: No such file or directory
···

readme：
···
cmdtool（在 WSL 中运行）
用法: cmdtool [选项]...
  wcmd: 使用 cmd.exe /c 运行 Windows 程序。
  wstart: 使用 cmd.exe /c start 运行 Windows 程序。
  update: 检查更新，如果有更新可以直接升级。
  killall: 杀死所有的 WSL 进程。
  install cbwin: 安装 cbwin。
  install dash: 安装 Cygwin 中的 dash（用于调试）。
  install busybox: 安装 Cygwin 中的 busybox（用于调试）
···

**Comment by mskyaxl** [comment]
Just type cmd tool in your bash and the help will appear :)
mosky@MOSKY-PC:~$ cmdtool
Usage: /mnt/c/Users/mosky/wsl-terminal/cmdtool [OPTION]...
  wcmd: run Windows programs with cmd.exe /c.
  wstart: run Windows programs with cmd.exe /c start.
  wstartex file|url: like wstart, but use WSL file path.
  update: check the latest wsl-terminal version, and upgrade it.
  killall: kill all WSL process.
  install winpty: install Cygwin winpty.
  install dash: install Cygwin dash (for debugging).
  install busybox: install Cygwin busybox (for debugging).
