### ISSUE TITLE
Starting with v.0.8.8, clicking a tmux pane no longer makes it active...

### ISSUE THREAD

**Issue by DavidCannon** [mskyaxl/wsl-terminal#117]
Starting with v.0.8.8, if you make a different app/window active, and then you click back onto a wsl-terminal  tmux pane, it no longer activates the pane. The first click will only activate the entire window, so you have to click a second time in order to activate the specific pane, if different than the previously active one.

It works perfectly in v.0.8.7 but stopped working in v.0.8.8. Do you need any other details?

**Comment by mskyaxl** [comment]
Hi @DavidCannon I just took over this repo and I am going through all the issues, 

I was not able to reproduce it on the latest version. Have you tried on the latest version?

**Comment by DavidCannon** [comment]
It's been working fine, so I assume it was fixed a while back. Thanks for the follow-up. Closing this issue now. 👍
