### ISSUE TITLE
not response after switch window

### ISSUE THREAD

**Issue by TestSmirk** [mskyaxl/wsl-terminal#118]
windows 1803
wsl ubuntu version 18
wsl-terminal version v0.8.11

When is use `alt + f2` create a new window and ` ctrl + tab ` to switch wsl window  the last window is not response.

![20180808184853](https://user-images.githubusercontent.com/12248888/43832974-b625a964-9b3b-11e8-9176-a168ad02081f.png)

**Comment by mskyaxl** [comment]
this is not reproducible on 0.9.0. I will close it. If you can reproduce it please re-open.
