### ISSUE TITLE
组合键支持存在问题

### ISSUE THREAD

**Issue by jinwei233** [mskyaxl/wsl-terminal#120]
比如我绑定了一个 Ctrl-Alt-g 组合键，现在只能识别为 Ctrl-g
![image](https://user-images.githubusercontent.com/243645/44022407-145542ce-9f1a-11e8-88eb-61ea4a4b2346.png)

还有组合键 Ctrl+Shift+n 显示的是
![image](https://user-images.githubusercontent.com/243645/44022466-42f80c7e-9f1a-11e8-8815-fd845fae54a4.png)

**Comment by mskyaxl** [comment]
I don't think I understand the issue. Google translate did not help me much. Can you please reiterate in English?
Thanks!

**Comment by mskyaxl** [comment]
closing because no further details are given
