### ISSUE TITLE
.bash_profile not loading automatically when i open wsl-terminal

### ISSUE THREAD

**Issue by LJHayman** [mskyaxl/wsl-terminal#121]
is there a way to get this file to load as soon as i open the wsl-terminal?

currently i have to source it every time

thanks!

edit-

and when i try to add a source command to open-wsl like:
`(e.g. -c "echo a b; echo c; cat")`
the process dies and the screen closes as soon as it's executed

**Comment by TylerZhang1993** [comment]
1.Modify shell=/bin/bash in etc/wsl-terminal.conf file to shell=/bin/bash--login
2. or you can modify .bashrc file to add the relative command

**Comment by mskyaxl** [comment]
or use 4-create-start-menu-shortcut-login-shell.js to create a shortcut for you :)
