### ISSUE TITLE
下载后运行open-wsl.exe报错

### ISSUE THREAD

**Issue by liang1224** [mskyaxl/wsl-terminal#128]
![tim 20181008164813](https://user-images.githubusercontent.com/12098363/46599429-f16eee00-cb19-11e8-8ed4-33b08a77f6a4.png)

系统版本： windows 10 1803 x64
wsl-terminal版本： 0.8.11
软件目录： c:\Program Files\wsl-terminal
磁盘格式： NTFS

**Comment by liang1224** [comment]
项目没有人维护了吗?

**Comment by mskyaxl** [comment]
closing as this was for a reale old version. please reopen a new one if it is still reproducible and I'll try to help :slightly_smiling:
