### ISSUE TITLE
WSL-Terminal crash after changing root mount path in '/etc/wsl.conf'

### ISSUE THREAD

**Issue by m-kutnik** [mskyaxl/wsl-terminal#129]
# Versions
wsl-terminal: 0.8.11
Windows 10 Pro 1809
Used shell version: WSL (Ubuntu 18.04.01)

# Problem description
The Spring 2018 stable edition of Windows now supports adding in a wsl.conf file where you can customize the root mount location `( default: /mnt )`. Docker for Windows expects things to exist at `/c` instead of `/mnt/c` when it comes to mounting volumes.

# Steps to reproduce
1. Configure `/etc/wsl.conf`:
```
[automount]
enabled = true
root = /
```
2. Sign Out, Sign In, or Restart PC
3. Open WSL-Terminal -> crash

# Fix

As pointed [here](https://github.com/rprichard/wslbridge/issues/22) problem is `wslbridge` related.
Fixed `wslbridge` binaries: [comment](https://github.com/Maximus5/ConEmu/issues/1538#issuecomment-386838630), [files](https://www.dropbox.com/s/i8z8gm80wfrcr91/wslbridge-wslpath.7z?dl=0) (by @Maximus5)

Everything works well.

**Comment by mcfiredrill** [comment]
Is this fixed? I'm still seeing it in the latest version...

**Comment by m-kutnik** [comment]
@mcfiredrill if not, download [fixed binaries](https://www.dropbox.com/s/i8z8gm80wfrcr91/wslbridge-wslpath.7z?dl=0) and move them to 'C:\..[path-to-your-wsl]..\bin'

**Comment by mcfiredrill** [comment]
Hmm tried those binaries and its still crashing for me...

**Comment by AlisterH** [comment]
It seemed to me to be caused by the existence of /etc/wsl.conf - no problem if I removed it, but not working even if it was any empty file.

No difference with the "fixed" binaries.

But now (same day) it is still not working even though there is no /etc/wsl.conf at the moment.  So I'm inclined to think there's something going on in Windows or WSL itself that causes the problem.

**Comment by anribras** [comment]
"fixed" binaries not worked for me , too. @m-kutnik
