### ISSUE TITLE
老哥们谁知道mintty如何更新

### ISSUE THREAD

**Issue by shuohao** [mskyaxl/wsl-terminal#130]
我打开wsl-terminal提示mintty2.9.3可用，但是进到mintty的主要下载的只有源码

**Comment by chenjuntong** [comment]
要等作者打包更新进去我们才能用

**Comment by goreliu** [comment]
去 http://mirrors.kernel.org/sourceware/cygwin/x86_64/release/mintty/ 下载然后替换 mintty.exe 文件。

**Comment by pinggit** [comment]
我替换了mintty.exe, 但是启动wsl-terminal时得到这个错误：

manpath: can't set the locale; make sure $LC_* and $LANG are correct

后果是不能键入中文
