### ISSUE TITLE
Vim copy/paste

### ISSUE THREAD

**Issue by HaraldWeber** [mskyaxl/wsl-terminal#131]
Whith this option in .vimrc I can copy/paste between windows and wsl when i start vim from a wsl terminal.
```
" make yank copy to the global system clipboard (windows)
set clipboard=unnamed
```
But I cant when I start vim from vim.exe. What is the difference between the two start up methods? Is there a workaround or fix available?

**Comment by mskyaxl** [comment]
Hi, probably it's too late for an answer. I took over this recently. The difference is that for vim.exe / emacs.exe etc the shell is not started with --login.

I haven't considered this scenario. I will think about it, maybe it makes sense to have  -l also for this situation.

**Comment by mskyaxl** [comment]
but for me it works with both, I have  '''set clipboard^=unnamed,unnamedplus''' in my vimrc
https://github.com/mskyaxl/dotfiles/blob/master/vim/vimrc

**Comment by mskyaxl** [comment]
closing as no reply was given.
