### ISSUE TITLE
Can't set image background (while can in cygwin)

### ISSUE THREAD

**Issue by AsaeBega** [mskyaxl/wsl-terminal#132]
I can't set image background in  minttyrc file, but I can do this in cygwin.
![1](https://user-images.githubusercontent.com/37773688/47370800-2caf1680-d6ef-11e8-9e2d-3c15ee56d4cf.png)
![2](https://user-images.githubusercontent.com/37773688/47370803-2d47ad00-d6ef-11e8-9657-6a017a4f9995.png)

**Comment by mskyaxl** [comment]
It works if you provide the right path. 
![image](https://user-images.githubusercontent.com/5708771/79112613-3c0c9e80-7d7f-11ea-8d33-c5e38bc6046c.png)
 Please be more specific.
