### ISSUE TITLE
bug when run ~/.zshrc

### ISSUE THREAD

**Issue by vinthony** [mskyaxl/wsl-terminal#134]
![image](https://user-images.githubusercontent.com/4397546/49694632-b2682200-fbc8-11e8-9365-283515c69c15.png)

**Comment by fengzhao** [comment]
你的 .zshrc文件中有语法错误吧

**Comment by vinthony** [comment]
@fengzhao 没有，用原生bash和wsltty打开都没问题

**Comment by mskyaxl** [comment]
can you please share your .zshrc?

**Comment by mskyaxl** [comment]
closing as no answer was given
