### ISSUE TITLE
开启tmux无法粘贴

### ISSUE THREAD

**Issue by fengzhao** [mskyaxl/wsl-terminal#135]
开启tmux之后，从windows中复制的内容，无法在wsl-terminal中粘贴

**Comment by szthanatos** [comment]
按住Shift再右键就能看到菜单了。
或者Ctrl+Ins复制，Shift+Ins粘贴。

**Comment by fengzhao** [comment]
> 按住Shift再右键就能看到菜单了。
> 或者Ctrl+Ins复制，Shift+Ins粘贴。

谢谢了。

**Comment by fengzhao** [comment]
@szthanatos  请问开启tmux后，如何从已经从终端中已经输入过的命令中复制内容呢？如下图，我复制这个命令到windows中。应该怎么操作啊

![image](https://user-images.githubusercontent.com/6206340/50322438-e966fd80-050f-11e9-867e-a6fc957c2a60.png)

**Comment by mskyaxl** [comment]
Please follow the issue https://github.com/mskyaxl/wsl-terminal/issues/144

I do have a similar setup and I made it work only with a xserver.

**Comment by fengzhao** [comment]
等了快两年了，已经换成windows terminal了
