### ISSUE TITLE
wslbridge error: failed to start backend process

### ISSUE THREAD

**Issue by lymansix** [mskyaxl/wsl-terminal#137]
`wslbridge error: failed to start backend process note: backend error output: wslbridge-backend: wslbridge-backend.cc:45: int {anonymous}::connectSocket(int, const string&): Assertion connectRet == 0' failed.`

**Comment by AlaaZorkane** [comment]
![image](https://user-images.githubusercontent.com/2952507/51836187-f1307380-22ff-11e9-96bb-546ad44f028f.png)
Same issue here...

**Comment by mskyaxl** [comment]
not reproducible on version 0.9.0

**Comment by Purplebeard** [comment]
Same issue again
