### ISSUE TITLE
安装cygwin后无法打开open-wsl了

### ISSUE THREAD

**Issue by kinghuin** [mskyaxl/wsl-terminal#140]
没装cygwin前可以正常打开open-wsl，
安装之后运行之后不会弹出任何窗口

尝试了https://github.com/goreliu/wsl-terminal/issues/95，wslbridge.exe 可以正常打开
尝试了https://github.com/goreliu/wsl-terminal/issues/36，
`wslbridge bash -c pwd` 可以正常打开，
但  `mintty -h error -e /bin/wslbridge -t bash` or `mintty -h error -e /bin/wslbridge bash -c 'pwd;sleep 10'` 没有弹窗

**Comment by wherebubugs** [comment]
之前采用的是wsl-terminal-tabbed-0.8.12
现改用wsl-terminal-0.8.12则可以正常打开。

I can't open "open-wsl" in "wsl-terminal-tabbed-0.8.12 " after installing cygwin.
In details:
No window shows and the file "mintty.exe.stackdump" is created in the folder.
Then I change to use the "open-wsl" in "wsl-terminal-0.8.12", it works.

**Comment by Adiwon** [comment]
+1
没有安装Cygwin，同样是tabbed0.8.12无法运行，普通版可以。

**Comment by mskyaxl** [comment]
This was reported already. I will be removing fatty in the future. Please use https://github.com/mskyaxl/wsl-terminal/issues/178 for further discussions.
