### ISSUE TITLE
one line install command fails

### ISSUE THREAD

**Issue by bbrendon** [mskyaxl/wsl-terminal#142]
`bash -c "wget https://github.com/goreliu/wsl-terminal/releases/download/v0.8.12/wsl-terminal-0.8.12.7z && 7z x wsl-terminal-0.8.12.7z"`

Results: 
`/bin/bash: 7z: command not found`

**Comment by keikun17** [comment]
you need 7z `sudo apt-get install p7zip-full`

**Comment by bbrendon** [comment]
Maybe update the docs?


`sudo apt-get install p7zip-full && bash -c "wget https://github.com/goreliu/wsl-terminal/releases/download/v0.8.12/wsl-terminal-0.8.12.7z && 7z x wsl-terminal-0.8.12.7z"`
