### ISSUE TITLE
How to incorporate into cmder?

### ISSUE THREAD

**Issue by lonelykid** [mskyaxl/wsl-terminal#146]
Currently I'm putting the target of the automatically generated .lnk into cmder. It works just fine (BTW, the windows GUI won't display the whole target since it's too long, bug for Microsoft). However, shortcut like ctrl+tab to switch tab won't work. I guess replace the wslbridge by the one provided by cmder might help.

**Comment by mskyaxl** [comment]
Hi, 
I'm not using cmder but I'm willing to help.
What I don't understand is why do you want to incorporate this into cmder and not directly the wslbridge.... wsl-terminal is more like a wrapper that calls mintty in wslMode(using wslbride)

**Comment by lonelykid** [comment]
Thanks...I've been using Windows Terminal now. I just gave it another try. Then I found out that it all stop working, both wsl-terminal and directly using wslbridge(embedded in cmder). It seems wslbridge is no longer maintained. After switching to wslbridge2, it works with no issue. So maybe it's  wslbridge issue.
