### ISSUE TITLE
全角符无法显示

### ISSUE THREAD

**Issue by yangkghjh** [mskyaxl/wsl-terminal#147]
➜ 显示为方框

**Comment by mskyaxl** [comment]
mosky@MOSKY-PC:~$ 显示为方框
显示为方框: command not found
mosky@MOSKY-PC:~$

It is shown like this for me(version 0.9.0). Can you please confirm that the issue is not present anylonger?

**Comment by yangkghjh** [comment]
Yes, it has been fixed.

Thank you for the work.
