### ISSUE TITLE
wsl-terminal terminating right after logging in

### ISSUE THREAD

**Issue by xXBeekeyXx** [mskyaxl/wsl-terminal#149]
When logging in as a user (in arch linux wsl), wsl-terminal immediately closes itself.

**Comment by mskyaxl** [comment]
can you please try it on the latest wsl-terminal? If this is reproducible please provide the following:

1. your wsl-terminal configuration file?
2. your .profile or .bashrc or .zshrc - depending on the shall you're using.

and afterwards I will have a look and try to support :)

**Comment by mskyaxl** [comment]
closing as no reply was given :)
