### ISSUE TITLE
Additional Window cannot be launched from Taskbar Icon

### ISSUE THREAD

**Issue by thehallofshields** [mskyaxl/wsl-terminal#152]
In most Windows Apps you're able to right-click the taskbar icon to launch an additional application window. A good example would be right-clicking on the taskbar icon for Firefox or Chrome.

With open-wsl, when you rright-click the taskbar icon and select 'Terminal', your new window spits out the error: "Failed to run '/bin/bash': No such file or directory".

**Comment by mskyaxl** [comment]
this is working on 0.9.x versions :)
