### ISSUE TITLE
cmdtool update with wsl-terminal-tabbed

### ISSUE THREAD

**Issue by jmonfar** [mskyaxl/wsl-terminal#156]
If you have installed the wsl-terminal-tabbed release, using the cmdtool update mechanism gets the wsl-terminal (not tabbed) version and overrides the one you have. It sees that the cmdtool script does not contemplate the -tabbed version.

**Comment by mskyaxl** [comment]
That is correct but the tabbed version is currently broken (please see #178 ).

Instead of fixing this I would like to merge the two releases in the future and remove the separate binary for the tabbed version.
