### ISSUE TITLE
directory color is UNREADABLE when I type ls command

### ISSUE THREAD

**Issue by chengdanhao** [mskyaxl/wsl-terminal#157]
the default color scheme is hard to read
![default](https://user-images.githubusercontent.com/11373523/59029340-a2d44800-8890-11e9-9e8b-cc009d1f6011.png)

when I use wsl-terminal, I tried all color theme, it becomes unreadable,
![wsl-terminal](https://user-images.githubusercontent.com/11373523/59029339-a23bb180-8890-11e9-9ba8-f4c1024d3513.png)

**Comment by murphypei** [comment]
same issue

**Comment by mskyaxl** [comment]
have you tried to change the theme? I think the zsh theme does not match the configured mintty theme in wsl-terminal.

**Comment by mskyaxl** [comment]
or even using this plugin for zsh?

https://github.com/joel-porquet/zsh-dircolors-solarized
