### ISSUE TITLE
crash after upgrading to WSL 2

### ISSUE THREAD

**Issue by njzjz** [mskyaxl/wsl-terminal#159]

**Comment by transtone** [comment]
https://github.com/rprichard/wslbridge/issues/44

**Comment by Biswa96** [comment]
Cygwin now has Windows ConPTY support. See [this commit][1]. Released in Cygwin 3.1.0-0.3 test build. So, `wsl.exe` and other Windows console programs can be executed directly in mintty, no need to use wslbridge or winpty related programs. 

[1]: https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by transtone** [comment]
@Biswa96  what a good news!

**Comment by TTTPOB** [comment]
same problem. Any solution at daily-user-level? I think what Biswa96 said is more like a developer level solution...

**Comment by Biswa96** [comment]
You can use [wsltty][1] which has WSL2 support now.

[1]: https://github.com/mintty/wsltty

**Comment by mskyaxl** [comment]
Fixed
