### ISSUE TITLE
open-wsl.exe window closes immediately, mintty.exe Failed to run '/bin/bash': No such file or directory

### ISSUE THREAD

**Issue by henkson** [mskyaxl/wsl-terminal#160]
I have been using wsl-terminal 0.8.13 successfully, but it suddenly stopped working.

I have read issues #36 and #63, but I did not find a solution.

Using the `wslbridge` command did not really help:
```
C:\wsl-terminal\bin>wslbridge bash -c pwd

C:\wsl-terminal\bin>wslbridge echo abc & echo %errorlevel%
-2147483647
```

When running `mintty.exe` directly, a new window opens and gives this error:
```
/bin/bash: Exit 126.
Failed to run '/bin/bash': No such file or directory
```

However, when typing `bash` directly at the windows cmd prompt, it starts without problem:
```
C:\wsl-terminal\bin>bash
me@machine:/mnt/c/wsl-terminal/bin$
```
or
```
C:\wsl-terminal\bin> bash -c pwd
/mnt/c/wsl-terminal/bin
```

**Comment by henkson** [comment]
Apparently, I screwed up myself by changing the `.bashrc` and `.profile` files. Restoring them, fixed my problem.

**Comment by henkson** [comment]
Reopen: I don't know what temporarily fixed it, but it is broken again. I even re-installed my entire Ubuntu WSL, but I still get the error.

**Comment by priyadarshan** [comment]
I am having exact same issue.

**Comment by ifeue** [comment]
same issue.

**Comment by itsjef** [comment]
Same issue, refer: https://github.com/mintty/wsltty/issues/156
