### ISSUE TITLE
change font color

### ISSUE THREAD

**Issue by arasHi87** [mskyaxl/wsl-terminal#164]

**Comment by arasHi87** [comment]
How can i cnange font color

![圖片](https://user-images.githubusercontent.com/33758217/62407882-1b862500-b5f2-11e9-99fc-7f246d111fb4.png)

**Comment by mskyaxl** [comment]
have you tried changing the background color of the theme? (right click->options -> Looks -> theme)?

**Comment by arasHi87** [comment]
I forgot why that time I can't change font color, but I fixed it now, I think maybe is WSL's problem or just I am too fool that time to do wrong setting, all in all, I fixed it, thx !
![圖片](https://user-images.githubusercontent.com/33758217/78851217-d309eb80-7a4b-11ea-91c1-416349f4ce1e.png)
