### ISSUE TITLE
CTRL in emacs does not work

### ISSUE THREAD

**Issue by AddictArts** [mskyaxl/wsl-terminal#165]
It prints into the editor ;5u for example. This does not happen in wsl bash via the ubuntu launcher.

**Comment by mskyaxl** [comment]
Sorry, I am more a vim user than an emacs user. In fact I have never used emacs. Can you please help me with a set of steps to reproduce?

Thanks!

**Comment by AddictArts** [comment]
$ emacs .bashrc

Hit CTRL, you will see it

Can't CTRL-D, etc. You'll have to kill wsl-terminal to exit emacs and everything else.

**Comment by nanjj** [comment]
My emacs works well with `CTRL-d`, but not `ALT-d`. In fact it's not emacs setting problem. You can reproduce the same problem on bash, type something and type `ALT - d`(delete the whole word), you can see it, no response. But you can do it via `shift - alt - d`, to delete the whole word. The workaround works in emacs, also.

**Comment by nanjj** [comment]
And I just found `Alt -D` may not be related with wsl-terminal. WSL has this problem too.

**Comment by mskyaxl** [comment]
![CTRL working on 0 9 0](https://user-images.githubusercontent.com/5708771/79078975-6e30e880-7d0c-11ea-8508-cb4e49983940.gif)

**Comment by mskyaxl** [comment]
any feedback?

**Comment by AddictArts** [comment]
Thanks for asking and thanks for the updates. I'm back on a Mac for the moment, so I don't have any feedback. Thanks again. Cheers
