### ISSUE TITLE
Vim search history up/down arrow keys do not work

### ISSUE THREAD

**Issue by srchulo** [mskyaxl/wsl-terminal#166]
When I'm using vim and type `/` and then enter a few searches, if I hit `/` to start a new search and then hit the up and down arrow keys to go through my search history, I just get these:

`<UP><UP><DOWN><DOWN>`

**Comment by srchulo** [comment]
Actually, it's possible this is because the server I was on had an older version of vim. When logging into a newer server, I do not see this issue.

**Comment by mskyaxl** [comment]
which vim are you using? On vim VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
this is working :)
