### ISSUE TITLE
老铁,是我姿势不对?

### ISSUE THREAD

**Issue by d1y** [mskyaxl/wsl-terminal#167]
在商店装的`ubuntu`, 我姿势不对吗?

![image](https://user-images.githubusercontent.com/45585937/64316789-77284180-cfe8-11e9-8f97-e25ba4508b56.png)

**Comment by viperauter** [comment]
我也是这样的

**Comment by d1y** [comment]
> 我也是这样的

我的已经解决了, 貌似是我刚装好需要重启的, 重启之后打开应该就可以了

**Comment by viperauter** [comment]
> > 我也是这样的
> 
> 我的已经解决了, 貌似是我刚装好需要重启的, 重启之后打开应该就可以了
我重启了也不顶用了
