### ISSUE TITLE
WSL terminal hangs when opening options menu

### ISSUE THREAD

**Issue by bobf32** [mskyaxl/wsl-terminal#168]
Open WSL terminal. Alt-space to bring up menu, select options. 

Hang.

**Comment by mskyaxl** [comment]
which version @bobf32 ?

Can you share your config file?

**Comment by bobf32** [comment]
Unfortunately not. Since reporting this problem I have upgraded a number of times. Currently on wsltty 3.1.0.2 and haven't had this problem for some time now.

**Comment by mskyaxl** [comment]
ok :) I'll close this then :)
