### ISSUE TITLE
Solarized dark is not properly set unless I go back to Options to select it

### ISSUE THREAD

**Issue by stephane-rouleau** [mskyaxl/wsl-terminal#169]
When I open a new terminal using open-wsl, the default color appears to be bright white.

I go to options, leave everything as is (base16-solarized-dark.minttyrc), use "Apply" (or "Save") and the colors revert to the lighter gray of Solarized Dark.

I need to do this for every new terminal I open; any way to pass an option to change the theme when opening a terminal?

Thanks!

**Comment by mskyaxl** [comment]
I don't have this issue on 0.9.0. Most probably there was an issue in mintty. Do you still have this issue?

Also I do like more this solarized theme than the one one provided with wsl-terminal. I am thinking of including it in the next releases.

**Comment by stephane-rouleau** [comment]
I just tried my first upgrade in place using ./cmdtool upgrade.

It seems to have fixed the issue, thanks!  However, 2 things of notes:

1) wsl-terminal/VERSION still says 0.8.3
2) cmdtool upgrade ended with

mv: cannot stat '../../bin/wslbridge2-backend': No such file or directory

Don't know if that's important or not?

Thank you!

**Comment by mskyaxl** [comment]
the upgrade is broken after I added support for WSL2. I'm sorry but you'll have to update manually.

**Comment by stephane-rouleau** [comment]
Ah, okay -- I'll look at the documentation to see how to do this.  Thanks!

**Comment by stephane-rouleau** [comment]
I did a clean install and the bug came back.  Not a biggie...

**Comment by mskyaxl** [comment]
I am trying to reproduce. WSL1 or WSL2?(I have 2 machines, one with wsl1 and one with 2) Do you have any *.sh file to set your theme running in .profile or .bashrc or at startup like this: https://github.com/karlin/mintty-colors-solarized/blob/master/mintty-solarized-dark.sh

**Comment by stephane-rouleau** [comment]
WSL1.

I call a copy of mintty-solarized-dark.sh in my .bashrc; however it looks like it had the following three extra lines:

echo -ne '\e]10;#eee8d5\a'  # foreground
echo -ne '\e]11;#002b36\a'  # background
echo -ne '\e]12;#859900\a'  # cursor

Which overrode the foreground and background...  So I can look stupid on the Internet.  :(  Not sure why this was there, probably a leftover from when I was using Cygwin.

You may close this ticket, and forever shame me.

**Comment by mskyaxl** [comment]
no issue, I'm glad this got solved :)
