### ISSUE TITLE
WSL2 with open-wsl?

### ISSUE THREAD

**Issue by kkuhle** [mskyaxl/wsl-terminal#171]
Is this expected to work?  If anyone has gotten it to work, any pointers on what to do?  I did notice that wsltty released an update https://github.com/mintty/wsltty/releases/tag/3.0.6 for it to work with WSL V2.  I'm guessing we might need a similar update from @goreliu?

**Comment by mskyaxl** [comment]
+1 That would be great! I got used to this terminal.

**Comment by TTTPOB** [comment]
same problem

**Comment by mskyaxl** [comment]
I had some time to spare so I've updated open-wsl to support wsl2 also.
The changes are in #173.

**Comment by TTTPOB** [comment]
> 
> 
> I had some time to spare so I've updated open-wsl to support wsl2 also.
> The changes are in #174.

thank you! I think I will use your fork before the author merge your pr

**Comment by mskyaxl** [comment]
I also did a release :) 0.9.0 :)
