### ISSUE TITLE
wsl2 can not work

### ISSUE THREAD

**Issue by shuohao** [mskyaxl/wsl-terminal#172]
wsl2 can not work

**Comment by CyrilTaylor** [comment]
I got a better solution [Terminus](https://github.com/Eugeny/terminus)

**Comment by shuohao** [comment]
> I got a better solution [Terminus](https://github.com/Eugeny/terminus)

启动太慢，而且性能差，也没有鼠标右键当前目录打开这种功能

**Comment by mskyaxl** [comment]
Have you tried with the latest release?
