### ISSUE TITLE
请问中文页面怎么实现的

### ISSUE THREAD

**Issue by HoldenWang** [mskyaxl/wsl-terminal#175]
请教这个中文说明页面怎么实现的，https://goreliu.github.io/wsl-terminal/README.zh_CN.html，我在goreliu.github.io项目中没有看到对应的文件啊，我觉得这个不错想学习下。

**Comment by goreliu** [comment]
页面是 GitHub 内置的 jekyll 构建的，主题配置文件：https://github.com/mskyaxl/wsl-terminal/blob/master/_config.yml
