### ISSUE TITLE
运行open-wsl.exe时提示"Could not load icon: C:\Users\user\wsl-terminal\open-wsl.exe: 系统找不到指定的文件"

### ISSUE THREAD

**Issue by nukemiko** [mskyaxl/wsl-terminal#176]

**Comment by mskyaxl** [comment]
ca you please provide more details? such as:

where did you install wsl-terminal?
which version of wsl-terminal are you using?

Thanks

**Comment by mskyaxl** [comment]
closing as no reply was given
