### ISSUE TITLE
v0.9 mintty.exe crashes

### ISSUE THREAD

**Issue by valsamis-d** [mskyaxl/wsl-terminal#178]
Hi,

**EDIT:** This behavior is observed in 'tabbed' version only

After running "wsl-terminal.exe" I get the following in "mintty.exe.stackdump":

```
Exception: STATUS_ACCESS_VIOLATION at rip=00100427D9C
rax=0000000000000000 rbx=000000000000031A rcx=0000000000000000
rdx=0000000000000000 rsi=0000000080000001 rdi=FFFFFFFFFFFFFFFF
r8 =0000000000000000 r9 =86BCA1AF286BCA1B r10=0000000000000000
r11=0000000000000246 r12=0000000004200ABA r13=0000000004200ABA
r14=0000000000000000 r15=0000000000000000
rbp=00000000FFFFBF90 rsp=00000000FFFFBEE0
program=G:\IGT\PApps\WSLTerminal09\bin\mintty.exe, pid 496, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFBF90  00100427D9C (FFFFFFFFFFFFFFFF, 00002F10900, 00002F108B0, 000FFFFBF40)
000FFFFBF90  001004255E6 (00000000001, 00000000000, 00000000000, 000FFFFC028)
000FFFFC1D0  7FF812665B6D (001004249E0, 00004200ABA, 001004249E0, FFFFFFFFFFFFFFFF)
000FFFFC1D0  7FF81266517C (001004C6500, FFFFFFFFFFFFFFFF, 00001281A20, 00000000000)
0000000031A  7FF812664EE8 (00000000000, 00004200ABA, 00140000000, 00000000000)
00004200ABA  7FF80F1AF03D (000FFFFC330, 00080000000, 001004C6560, 00080000000)
000FFFFC330  0010045066C (001801A3F9C, 000FFFFCC73, 0018035DF88, 00180291A60)
000FFFFCCD0  0018004A826 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180048353 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048404 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

Any ideas?

Thank you
Dimitrios

**Comment by stephand** [comment]
I got a similar thing happening as of today, and also with 0.8.13-tabbed: 

Exception: STATUS_ACCESS_VIOLATION at rip=00100424000
rax=0000000000000000 rbx=0000000000000001 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000001 rdi=0000000000000000
r8 =0000000000000000 r9 =86BCA1AF286BCA1B r10=0000000000000000
r11=0000000000000246 r12=0000000000070CC2 r13=0000000100400000
r14=00000001004C6560 r15=00000008000667C0
rbp=0000000000000000 rsp=00000000FFFFC130
program=C:\Users\stephand\Downloads\Tools\wsl-terminal-tabbed-0.9.0\wsl-terminal-tabbed\bin\mintty.exe, pid 1391, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  00100424000 (7FF8CAC1C1AA, 00000000001, 00040000000, 00000000000)
000FFFFC290  0010042471A (00080000000, 00080000000, 001004C6560, 00000000000)
000FFFFC290  0010045197B (001801A3F9C, 000FFFFCC72, 0018035E008, 00180291A60)
000FFFFCCD0  0018004A826 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180048353 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048404 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by valsamis-d** [comment]
@stephand it looks like it was aut-upgraded to 0.9.0 (see the line) in exception:

> program=C:\Users\stephand\Downloads\Tools\wsl-terminal-tabbed-**_0.9.0_**\wsl-terminal-tabbed\bin\mintty.exe, pid 1391, thread main

**Comment by stephand** [comment]
From 0.8.13-tabbed below.  I used to use 0.8.13-tabbed without any issues, and suddenly as of today it and 0.9 are not working anymore.

Exception: STATUS_ACCESS_VIOLATION at rip=00100421B40
rax=0000000000000000 rbx=0000000000000001 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000001 rdi=0000000000000000
r8 =CCCCCCCCCCCCCCCD r9 =00000000160126DB r10=0000000000000000
r11=0000000000000246 r12=0000000000020ECE r13=0000000100400000
r14=00000001004A71E0 r15=0000000000000031
rbp=0000000000000000 rsp=00000000FFFFC130
program=C:\Users\stephand\Downloads\Tools\wsl-terminal-tabbed-0.8.13\wsl-terminal-tabbed\bin\mintty.exe, pid 1782, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  00100421B40 (7FF8CAC1C1AA, 00000000001, 00040000000, 00000000000)
000FFFFC290  0010042201A (00080000000, 00080000000, 001004A71E0, 00000000000)
000FFFFC290  00100448E2A (0018030AA00, 04949435341, 0018019814C, 000FFFFCC70)
000FFFFCCD0  0018004A816 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180048353 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048404 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by valsamis-d** [comment]
@stephand this is really strange... my 0.8.13 still works... Let's wait the expect opinion :)

**Comment by mskyaxl** [comment]
Hi, I will have a look over the weekend :)

**Comment by valsamis-d** [comment]
> 
> 
> Hi, I will have a look over the weekend :)

Thank you @mskyaxl !

**Comment by stephand** [comment]
My 0.8.13 now works again, too, on the same machine.  The only difference was that I now have 3x 1920x1080 screens and when it was crashing, I had a 3840x2160 (4k) @ 60Hz panel attached to my laptop.  Not that that makes a difference somewhere?

**Comment by mskyaxl** [comment]
it looks like the tabbed version uses an older version of mintty. I don't know yet what is the actual difference between them.

**Comment by mskyaxl** [comment]
I had some time to have a deeper look into this and I would rather try to merge the changes from fatty to mintty than maintaining 2 version of the wsl-terminal.

I had a look over mintty features and it looks like the tab support is not that far from becoming a reality.
https://github.com/mintty/mintty/issues/944

**Comment by stephand** [comment]
I suspect my issue with both new versions not working relate to my Windows build being too old?  At least WSLtty ( https://github.com/mintty/wsltty ) suggests that "Since release 3.0.5, WSLtty requires Windows version 1809 (the November 2018 release)."  And I am still on 1803 (not my own machine...).  Whatever the reason has probably also changed here so it is not supposed to work, I presume.

**Comment by mskyaxl** [comment]
Since mintty PR is not ready yet I spend some time looking into this and with the help of we managed to find the issue

https://github.com/paolo-sz/fatty/issues/2

Thanks! @paolo-sz
