### ISSUE TITLE
Readme is out of date on build instructions

### ISSUE THREAD

**Issue by cbartondock** [mskyaxl/wsl-terminal#186]
Readme refers to a build.bat which does not exist.

I couldn't get build.sh in scripts to work (sudo ./build.sh and source build.sh don't work), but perhaps I am missing something. Anyway updated build instructions would be nice.

**Comment by mskyaxl** [comment]
good point:) I'll update them :)

**Comment by cbartondock** [comment]
Will do ! For the time being I think I have it working.  Needed some chmod 777's, some dos2unix commands, and installing cygwin with the Devel packages enabled (I was too lazy to figure out which packages exactly are needed - but definitely make, gcc, and binutils). Waiting for cygwin to finish now

**Comment by cbartondock** [comment]
Yep! build succeeded. Here's what I needed to do to get it to work:

- Install Cygwin 64 and the Devel packages
- `sudo apt install dos2unix`
- `cd scripts; sudo chmod 777 *.sh; dos2unix *.sh`

**Comment by mskyaxl** [comment]
or you can run clone the repo from wsl and run wsl build.sh :)

**Comment by cbartondock** [comment]
Inside powershell? Neat! More issues regarding the readme, it doesn't seem to respect changing the default shell to /usr/bin/zsh in wsl-terminal.conf

Is there something else that needs to be done to get it to use the shell I choose?

**Comment by mskyaxl** [comment]
I have updated the readme :)

**Comment by cbartondock** [comment]
Nice!
