### ISSUE TITLE
how to install wsl-terminal

### ISSUE THREAD

**Issue by pinggit** [mskyaxl/wsl-terminal#189]
I've been using this for more than a year and everything was great.
today I wanted to install this wsl-terminal on another PC, but I simply could not figure it out how.
it seems for me the readme is really confusing.

suppose I have wsl installed, by default the windows cmd.exe is the terminal.
now from there, how do I install wsl-terminal?

run

  wsl bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"

in cmd.exe

then what is is the next?

"Run open-wsl.exe to open a WSL terminal in current directory (need to be on a local NTFS volume, more details)." 
I don't see open-wsl.exe after the 1st step...

**Comment by mskyaxl** [comment]
Hi! @pinggit,

As you might know already you can run wsl before installing wsl-terminal by simply typing `wsl` in the cmd.exe or in powershell. For this reason both ways are written in the README, separated by the word "**OR**" meaning that you can use either command line, either wsl.

Let's assume you are using cmd.exe:

Typically people install wsl-terminal either on C:/, either in their home directory by running:

` wsl bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)" `

If the installation is successful you should see a folder called `wsl-terminal` in the directory from which you called the command and in this folder `open-wsl.exe` is located.  Actually this did not change in the last year :) wsl-terminal was always installed to the current directory from which the command was called.

"need to be on a local NTFS volume," means that you should not install wsl-terminal inside the wsl filesystem but in the windows filesystem.

From step 2, nothing changed for the last 3 years.

I have rephrased it a little bit. Let me know if it a little bit clear.

**Comment by tatemilio** [comment]
Hello i have some issue when i install wsl-terminal.
I install it with :
wsl bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"
After installation i try to launch in cmd.exe open-wsl.exe, a terminal console launch and close immediatly. I don't have time to show error message :(

**Comment by skid9000** [comment]
@tatemilio Linked to #163 

@mskyaxl can you reopen this issue please ? This is still a thing.

**Comment by pinggit** [comment]
I got a new PC, following the instruction I got this error:

```
PS C:\Users\pings> wsl bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'qO'.
At line:1 char:102
+ ... sercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"
+                                                                   ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

bash: -c: option requires an argument
```

**Comment by pinggit** [comment]
0. Make sure you have 7z installed. On Ubuntu run: ```sudo apt install p7zip-full```, on Archlinux: run ```pacman -S p7zip```

<<< this is OK.

1. Change the directory to the folder where you want to install wsl-terminal to.

Make sure to install wsl-terminal in a the windows filesystem and not in the wsl filesistem. The installation folder needs to be on a local NTFS volume.

<<<OK

* Option 1: If you're in cmd.exe run:

```
wsl bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"
```

<<< this does not work (see previous comment)

* Option 2: If you're in wsl already run

```
bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)"
```

<<<this works

If you want to install the tabbed version you have to add a ```-t``` as parameter as shown bellow
```
bash -c "$(wget https://raw.githubusercontent.com/mskyaxl/wsl-terminal/master/scripts/install.sh -qO -)" '' -t
```

<<< I didn't try this.

2. Run `open-wsl.exe` to open a WSL terminal in current directory.

<<<from where I run open-wsl.exe ? I don't have it.

PS C:\Users\pings> open-wsl.exe
open-wsl.exe : The term 'open-wsl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ open-wsl.exe
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (open-wsl.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\pings>


3. Run `tools/1-add-open-wsl-terminal-here-menu.js` ([help](https://github.com/mskyaxl/wsl-terminal#tools)) to add a `Open wsl-terminal Here` context menu to `explorer.exe` (Run `tools/1-remove-open-wsl-terminal-here-menu.js` to remove it). If you are using Total Commander, [Use wsl-terminal with Total Commander](https://github.com/mskyaxl/wsl-terminal/wiki/Use-wsl-terminal-with-Total-Commander) may help you.

4. `run-wsl-file.exe` can run any `.sh` (or any others like `.py` `.pl`) script files in wsl-terminal, support `Open With` context menu in `explorer.exe`.

5. `vim.exe` can open any files with vim (in wsl-terminal), support `Open With` context menu in `explorer.exe`. `vim.exe` can be renamed to `emacs.exe` `nvim.exe` `nano.exe` `...` to open files in `emacs` `nvim` `nano` `...`.

**Comment by pinggit** [comment]
I think I figured it out... works fine now.
I was in a windows terminal, from there I started cmd.exe. for some reason it does not work in there.
standalone cmd.exe works fine.

and after step1, there will be a "wsl-terminal" folder in windows current folder, so needs to "cd wsl-terminal" and then run later commands.
